"""Modified Post table

Revision ID: ed2437169f18
Revises: fb0405119edb
Create Date: 2020-07-29 13:25:09.223934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2437169f18'
down_revision = 'fb0405119edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.Text(), nullable=False))
    op.drop_column('post', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
